/*
 * jQuery UI Widget 1.8
 *
 * Copyright (c) 2010 AUTHORS.txt (http://jqueryui.com/about)
 * Dual licensed under the MIT (MIT-LICENSE.txt)
 * and GPL (GPL-LICENSE.txt) licenses.
 *
 * http://docs.jquery.com/UI/Widget
 */
(function(b){var a=b.fn.remove;b.fn.remove=function(d,c){return this.each(function(){if(!c){if(!d||b.filter(d,[this]).length){b("*",this).add(this).each(function(){b(this).triggerHandler("remove")})}}return a.call(b(this),d,c)})};b.widget=function(c,f,d){var e=c.split(".")[0],h;c=c.split(".")[1];h=e+"-"+c;if(!d){d=f;f=b.Widget}b.expr[":"][h]=function(i){return !!b.data(i,c)};b[e]=b[e]||{};b[e][c]=function(j,i){if(arguments.length){this._createWidget(j,i)}};var g=new f();g.options=b.extend({},g.options);b[e][c].prototype=b.extend(true,g,{namespace:e,widgetName:c,widgetEventPrefix:b[e][c].prototype.widgetEventPrefix||c,widgetBaseClass:h},d);b.widget.bridge(c,b[e][c])};b.widget.bridge=function(c,d){b.fn[c]=function(h){var e=typeof h==="string",g=Array.prototype.slice.call(arguments,1),f=this;h=!e&&g.length?b.extend.apply(null,[true,h].concat(g)):h;if(e&&h.substring(0,1)==="_"){return f}if(e){this.each(function(){var i=b.data(this,c),j=i&&b.isFunction(i[h])?i[h].apply(i,g):i;if(j!==i&&j!==undefined){f=j;return false}})}else{this.each(function(){var i=b.data(this,c);if(i){if(h){i.option(h)}i._init()}else{b.data(this,c,new d(h,this))}})}return f}};b.Widget=function(d,c){if(arguments.length){this._createWidget(d,c)}};b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(e,d){this.element=b(d).data(this.widgetName,this);this.options=b.extend(true,{},this.options,b.metadata&&b.metadata.get(d)[this.widgetName],e);var c=this;this.element.bind("remove."+this.widgetName,function(){c.destroy()});this._create();this._init()},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled "+this.namespace+"-state-disabled")},widget:function(){return this.element},option:function(e,f){var d=e,c=this;if(arguments.length===0){return b.extend({},c.options)}if(typeof e==="string"){if(f===undefined){return this.options[e]}d={};d[e]=f}b.each(d,function(g,h){c._setOption(g,h)});return c},_setOption:function(c,d){this.options[c]=d;if(c==="disabled"){this.widget()[d?"addClass":"removeClass"](this.widgetBaseClass+"-disabled "+this.namespace+"-state-disabled").attr("aria-disabled",d)}return this},enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(d,e,f){var g=this.options[d];e=b.Event(e);e.type=(d===this.widgetEventPrefix?d:this.widgetEventPrefix+d).toLowerCase();f=f||{};if(e.originalEvent){for(var c=b.event.props.length,h;c;){h=b.event.props[--c];e[h]=e.originalEvent[h]}}this.element.trigger(e,f);return !(b.isFunction(g)&&g.call(this.element[0],e,f)===false||e.isDefaultPrevented())}}})(jQuery);