# -*- coding: utf-8 -*-

to_check = {
    "addr:housenumber": [ "*" ],
    "amenity": [
        "bank",
        "bar",
        "bench",
        "cafe",
        "clock",
        "college",
        "drinking_water",
        "fast_food",
        "fuel",
        "hospital",
        "parking",
        "pharmacy",
        "place_of_worship",
        "post_box",
        "post_office",
        "pub",
        "restaurant",
        "school",
        "shelter",
        "telephone",
        "university",
        "waste_basket"
    ],
    "barrier" : [ "*" ],
    "boundary" : [ "*" ],
    "bridge" : [ "*" ],
    "building": [
        "*",
        "church",
        "yes",
    ],
    "ele" : [ "*" ],
    "est_width": [ "*" ],
    "height" : [ "*" ],
    "hgv" : [ "*" ],
    "highway": [
        "bus_stop",
        "crossing",
        'cycleway',
        'footway',
        "motorway_junction",
        'path',
        "speed_camera",
        'steps',
        "stop",
        "street_lamp",
        "traffic_lights",
        ('streets', (
            'road',
            'service',
            'pedestrian',
            'living_street',
            'residential',
            'unclassified',
            'tertiary',
            'secondary_link',
            'secondary',
            'primary_link',
            'primary',
            'trunk_link',
            'trunk',
            'motorway_link',
            'motorway',
            'bus_guideway',
        )),
    ],
    "historic" : [ "*" ],
    "leisure": [
        "park",
        "pitch",
        "playground",
    ],
    "lit": [ "*" ],
    "maxspeed": [ "*" ],
    "mtb:scale:*": [ "*" ],
    "natural": [
        "tree",
    ],
    "note": [ "*" ],
    "office": [ "*" ],
    "parking:lane:*": [
        "*",
        "no_parking",
        "no_stopping",
    ],
    "place": [
        "*",
        "city",
        "hamlet",
        "locality",
        "suburb",
        "town",
        "village",
    ],
    "power": [
        "generator",
        "tower"
    ],
    "railway": [ "*" ],
    "sac_scale": [ "*" ],
    "shop": [ "*" ],
    "surface" : [ "*" ],
    "tactile_paving": [ "*" ],
    "tourism": [ "*" ],
    "tracktype" : [ "*" ],
    "traffic_calming" : [ "*" ],
    "tunnel" : [ "*" ],
    "type": [
        "restriction",
        "street",
    ],
    "waterway" : [
        "river",
        "*",
    ],
    "wheelchair": [ "*" ],
    "width" : [ "*" ]
}

